
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 
* DO NOT EDIT.
*
* Copyright (C) 2010-2021 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_AXI_GPIO_IN_DEVICE_ID,
		XPAR_AXI_GPIO_IN_BASEADDR,
		XPAR_AXI_GPIO_IN_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_IN_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_OUT_DEVICE_ID,
		XPAR_AXI_GPIO_OUT_BASEADDR,
		XPAR_AXI_GPIO_OUT_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_OUT_IS_DUAL
	}
};


